CREATE TABLE FARMACI( CODICE VARCHAR(3),
                        NOME VARCHAR(20),
                        CATEGORIA VARCHAR(50),
                        CONSTRAINT FARMACI_PK PRIMARY KEY(CODICE)) ;
                        
CREATE TABLE VENDITE( VID VARCHAR(3),
                        Farmaco VARCHAR(3) ,
                        Data1 DATE,
                        QTA INTEGER,
                        CONSTRAINT VENDITE_PK PRIMARY KEY(VID),
                        CONSTRAINT VENDITE_FK FOREIGN KEY(Farmaco) REFERENCES FARMACI(CODICE)) ;
                        
INSERT INTO FARMACI VALUES( 001, 'Aulin' , 'A' ) ;
INSERT INTO FARMACI VALUES( 002, 'Oki' , 'Anti-Infiammatorio' ) ;
INSERT INTO FARMACI VALUES( 004, 'Oko' , 'Anti-Infiammatorio' ) ;
INSERT INTO FARMACI VALUES( 003, 'Brufen' , 'A' ) ;*/
INSERT INTO VENDITE VALUES( 01 , 001 , '10-OCT-17' , 30 ) ;
INSERT INTO VENDITE VALUES( 02 , 002 , '10-OCT-17' , 50 ) ;
INSERT INTO VENDITE VALUES( 03 , 004 , '10-OCT-17' , 80 ) ;
INSERT INTO VENDITE VALUES( 04 , 003 , '10-OCT-17' , 100 ) ;

SELECT F.CATEGORIA , SUM(V.QTA) AS Totale_Venduti
    FROM FARMACI F JOIN VENDITE V ON F.CODICE = V.VID 
    GROUP BY F.CATEGORIA ;
    
SELECT F.NOME AS FARMACO
FROM FARMACI F , VENDITE V
WHERE F.CATEGORIA = 'Anti-Infiammatorio'
AND F.CODICE = V.VID
AND V.QTA >= ALL( SELECT V1.QTA FROM VENDITE V1, FARMACI F1 WHERE V1.VID = F1.CODICE AND F1.CATEGORIA = 'Anti-Infiammatorio') ;

SELECT F.NOME AS FARMACO
FROM FARMACI F , VENDITE V
WHERE F.CATEGORIA = 'Anti-Infiammatorio'
AND F.CODICE = V.VID
AND V.QTA = ( SELECT MAX(V1.QTA) FROM VENDITE V1, FARMACI F1 WHERE V1.VID = F1.CODICE AND F1.CATEGORIA = 'Anti-Infiammatorio') ;