CREATE TABLE SQUADRA( CODICE VARCHAR(3),
                        NOME VARCHAR(20),
                        CITTA VARCHAR(20),
                        CONSTRAINT PK_SQ PRIMARY KEY(CODICE));

CREATE TABLE CALCIATORE( CODICETESSERA VARCHAR(3),
                            NOME VARCHAR(20),
                            COGNOME VARCHAR(30),
                            RUOLO VARCHAR(11),
                            ETA INTEGER,
                            SQUADRA VARCHAR(3),
                            CONSTRAINT FK_CA FOREIGN KEY(SQUADRA) REFERENCES SQUADRA(CODICE),
                            CONSTRAINT PK_CA PRIMARY KEY(CODICETESSERA)) ;
                            
INSERT INTO SQUADRA VALUES( '001' , 'NAPOLI' , 'NAPOLI' ) ;
INSERT INTO SQUADRA VALUES( '002' , 'MILAN' , 'MILANO' ) ;
INSERT INTO SQUADRA VALUES( '003' , 'INTER' , 'MILANO' ) ;
INSERT INTO CALCIATORE VALUES( '001' , 'ALESSIO' , 'ANDREOZZI' , 'ATTACCANTE' , 20 , '001' ) ;
INSERT INTO CALCIATORE VALUES( '002' , 'MARTINA' , 'DI VAIO' , 'ATTACCANTE' , 21 , '001' ) ;
INSERT INTO CALCIATORE VALUES( '003' , 'SARA' , 'ANDREOZZI' , 'ATTACCANTE' , 13 , '002' ) ;
INSERT INTO CALCIATORE VALUES( '004' , 'VINCENZO' , 'MOSCATO' , 'PORTIERE' , 50 , '003' ) ;

SELECT S.NOME , COUNT(*) NUM_GIOCATORI
FROM SQUADRA S JOIN CALCIATORE C ON S.CODICE = C.SQUADRA
GROUP BY S.NOME ;

SELECT S.NOME , COUNT(*) AS NUM_ATTACCANTI
FROM SQUADRA S, CALCIATORE C
WHERE S.CODICE = C.SQUADRA
AND C.RUOLO = 'ATTACCANTE'
GROUP BY S.NOME
HAVING COUNT(*) >= ALL( SELECT COUNT(*) FROM SQUADRA S1, CALCIATORE C1 WHERE S1.CODICE = C1.SQUADRA AND C1.RUOLO = 'ATTACCANTE' GROUP BY S1.NOME ) ;
