CREATE TABLE RAMI( CODICE VARCHAR(3),
                   DESCRIZIONE VARCHAR(30),
                   CONSTRAINT PK_RAMI PRIMARY KEY(CODICE)) ;

CREATE TABLE IMPIEGATI( MATRICOLA VARCHAR(3),
                        NOME VARCHAR(20),
                        COGNOME VARCHAR(30),
                        CODRAMO VARCHAR(3),
                        SALARIO INTEGER,
                        CONSTRAINT PK_IMPIEGATI PRIMARY KEY(MATRICOLA),
                        CONSTRAINT FK_IMPIEGATI FOREIGN KEY(CODRAMO) REFERENCES RAMI(CODICE)) ;

INSERT INTO RAMI VALUES('001','CONTABILITA') ;
INSERT INTO RAMI VALUES('002','INFORMATICA') ;
INSERT INTO RAMI VALUES('003','RISORSE UMANE') ;

INSERT INTO IMPIEGATI VALUES( '001' , 'ALESSIO' , 'ANDREOZZI' , '002' , 20000 ) ;
INSERT INTO IMPIEGATI VALUES( '002' , 'MARIO', 'ROSSI' , '001' , 15000 ) ;
INSERT INTO IMPIEGATI VALUES( '003' , 'GIUSEPPE' , 'VERDI' , '002' , 10000 ) ;
INSERT INTO IMPIEGATI VALUES( '004' , 'PINO' , 'MAURO' , '003' , 20000 ) ;
INSERT INTO IMPIEGATI VALUES( '005' , 'GUIDO' , 'LAMOTO' , '003' , 30000 ) ;

CREATE MATERIALIZED VIEW VISTA AS SELECT R.DESCRIZIONE AS DE , COUNT(*) AS CONTO FROM RAMI R JOIN IMPIEGATI I ON R.CODICE = I.CODRAMO GROUP BY R.DESCRIZIONE ;


SELECT R.DESCRIZIONE AS RAMO,COUNT(*) as occ, SUM( I.SALARIO ) AS SOMMA_SALARI
FROM RAMI R , IMPIEGATI I , VISTA V
WHERE R.CODICE = I.CODRAMO AND R.DESCRIZIONE = V.DE AND V.CONTO > 1 
GROUP BY R.DESCRIZIONE ;

CREATE MATERIALIZED VIEW VISTA2 AS SELECT I.COGNOME AS COGNOME FROM IMPIEGATI I , RAMI R WHERE I.CODRAMO = R.CODICE AND R.DESCRIZIONE = 'CONTABILITA' ;

SELECT I.COGNOME FROM IMPIEGATI I MINUS SELECT V.COGNOME FROM VISTA2 V ;