CREATE TABLE DIPARTIMENTO( ID VARCHAR(3),
                            NOME_D VARCHAR(10),
                            SEDE VARCHAR(20),
                            CONSTRAINT PK_DIP PRIMARY KEY(ID)) ;
CREATE TABLE ARTICOLO( ID VARCHAR(3),
                        NOME_A VARCHAR(10),
                        DESCRIZ VARCHAR(20),
                        CONSTRAINT PK_ART PRIMARY KEY(ID)) ;
CREATE TABLE ACQUISTA( ID_DIP VARCHAR(3), 
                        ID_ART VARCHAR(3),
                        PREZZO_A FLOAT,
                        CONSTRAINT FK_AC FOREIGN KEY(ID_DIP) REFERENCES DIPARTIMENTO(ID) ,
                        CONSTRAINT FK_AC2 FOREIGN KEY(ID_ART) REFERENCES ARTICOLO(ID),
                        CONSTRAINT PK_AC PRIMARY KEY(ID_DIP,ID_ART) ) ;

INSERT INTO DIPARTIMENTO VALUES( '001' , 'D1' , 'VIA 1' ) ;
INSERT INTO DIPARTIMENTO VALUES( '002' , 'D2' , 'VIA 2' ) ;
INSERT INTO ARTICOLO VALUES( '001' , 'S9' , 'TELEFONINO' ) ;
INSERT INTO ARTICOLO VALUES( '002' , 'BOH' , 'LETTO' ) ;
INSERT INTO ACQUISTA VALUES( '001' , '001' , 20 ) ;
INSERT INTO ACQUISTA VALUES( '001' , '002' , 30 ) ;
INSERT INTO ACQUISTA VALUES( '002' , '001' , 50 ) ;

SELECT D.NOME_D FROM DIPARTIMENTO D, ARTICOLO A, ACQUISTA AC WHERE
D.ID = AC.ID_DIP AND A.ID = AC.ID_ART AND A.DESCRIZ = 'TELEFONINO' ;

SELECT D.NOME_D FROM DIPARTIMENTO D MINUS ( SELECT D1.NOME_D FROM DIPARTIMENTO D1, ARTICOLO A1, ACQUISTA AC1 WHERE D1.ID = AC1.ID_DIP AND
                                            A1.ID = AC1.ID_ART AND A1.DESCRIZ <> 'TELEFONINO' GROUP BY D1.NOME_D  ) ;
