SELECT P.nome , SUM(V.qta_venduta) FROM PRODOTTI P , VENDITE V --1.1
WHERE P.codice = V.prodotto AND V.anno = 2016
GROUP BY P.nome ;

CREATE MATERIALIZED VIEW VENDITE16 AS SELECT P.codice AS COD FROM VENDITE V , PRODOTTI P WHERE V.prodotto = P.codice and V.anno = 2016 ;

SELECT P.nome FROM PRODOTTI P MINUS ( SELECT P1.nome FROM PRODOTTI P1 , VENDITE16 V1 WHERE P1.codice = V1.COD ) ; --1.2



SELECT U.cognome , SUM(C.QTA) FROM UTENTI U, CARRELLI C WHERE U.username = C.utente GROUP BY U.cognome ORDER BY SUM(C.QTA) ASC ; --2.1

CREATE MATERIALIZED VIEW MOSCATO AS SELECT C.utente AS ut FROM CARRELLI C , UTENTI U WHERE U.username = C.utente AND U.cognome = 'MOSCATO' ;

SELECT C.Prodotto FROM CARRELLI C MINUS ( SELECT C1.Prodotto FROM CARRELLI C1 , MOSCATO M WHERE M.ut = C1.Utente ) ;  --2.2




SELECT A.Categoria , AVG( M.Qta ) FROM ARTICOLI A , MOVIMENTAZIONI M WHERE A.Codice = M.Prodotto GROUP BY A.Categoria ; --3.1

SELECT A.Descrizione FROM ARTICOLI A WHERE A.Giacenza = ( SELECT MAX(A.Giacenza) FROM ARTICOLI A ) ;